### ISSUE TITLE
bower permission issue at openshift

### ISSUE THREAD

**Issue by erikwoo** [dbashford/mimosa-bower#29]
hi there.
I run mimosa on openshift.
when requiring mimosa bower. there's a permission issue when bower/node_modules/mkdirp trying to access ~/.local

node -e 'require("path/to/mimsoa-bower")'

---log--- 
Error: EACCES, permission denied '/var/lib/openshift/5258ab064**cf602000003/.local'
    at Object.fs.mkdirSync (fs.js:642:18)
    at sync (/var/lib/openshift/5258ab064382ecf602000003/app-root/runtime/repo/node_modules/mimosa-bower/node_modules/bower/node_modules/mkdirp/index.js:55:12)
    at sync (/var/lib/openshift/5258ab064382ecf602000003/app-root/runtime/repo/node_modules/mimosa-bower/node_modules/bower/node_modules/mkdirp/index.js:61:24)
    at sync (/var/lib/openshift/5258ab064382ecf602000003/app-root/runtime/repo/node_modules/mimosa-bower/node_modules/bower/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/var/lib/openshift/5258ab064382ecf602000003/app-root/runtime/repo/node_modules/mimosa-bower/node_modules/bower/node_modules/mkdirp/index.js:61:24)
    at Object.<anonymous> (/var/lib/openshift/5258ab064382ecf602000003/app-root/runtime/repo/node_modules/mimosa-bower/node_modules/bower/lib/core/resolvers/GitResolver.js:28:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by PixelWaffles** [comment]
@JasonGhent I'm not sure if this is still relevant to you after so many months, but I encountered this problem and solved it by adding conditionals around the execution code:

```
"postinstall": "if [ -d \"$OPENSHIFT_REPO_DIR\" ]; then (export HOME=\"$OPENSHIFT_REPO_DIR\"/..; bower install) else (bower install) fi",
```

It's a tad dirty (mostly due to the love hate relationship between .json and newlines), but it should be a much more elegant solution than including build code within the app proper.

**Comment by alexeychikk** [comment]
@DLDante 
I have done all the steps, but bower install still not working...
bash: /var/lib/openshift/556cbac95973ca8f8b000158/app-root/runtime/repo/node_modules/.bin/bower: No such file or directory

**Comment by deathmood** [comment]
Solved it with this `build` action hook:

```
if [ ! -d $OPENSHIFT_NODEJS_DIR/node_modules/bower ]
then
    cd $OPENSHIFT_NODEJS_DIR
    npm install bower
fi

cd $OPENSHIFT_HOMEDIR/app-root/repo
HOME=$OPENSHIFT_REPO_DIR bower install
cd $OPENSHIFT_HOMEDIR
```

**Comment by rdjs** [comment]
The fix referencing @ginsederp comment worked for me:

https://github.com/cainrus/repotracktor/commit/f3c856d8b4b666b00edd036febd6c2b75d625998

in package.json:

`"postinstall": "if [ -d \"$OPENSHIFT_REPO_DIR\" ]; then (export HOME=\"$OPENSHIFT_REPO_DIR\"/..; $(npm bin)/bower install) else ($(npm bin)/bower install) fi && npm run setup"`

**Comment by andrrrl** [comment]
I removed `bower` from dependencies in my `package.json`. I checked that openshift removed the package accordingly when `git push`'d, but I still get the permission error, any ideas how to fix? 
Again, removed `bower`, no longer is being used in my project, but still get that nasty error. Needless to say I tried all above fixes, none worked.

**Comment by AndyOGo** [comment]
How about Openshift version 3?
The environment variable `$OPENSHIFT_REPO_DIR` is gone there...
